open-power/secvarctl

Makefile, README.md, backends/edk2-compat/edk2-svc-generate.c, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-validate.c, backends/edk2-compat/include/edk2-svc.h, extraMbedtls/generate-pkcs7.c, include/err.h, secvarctl.1, secvarctl.c, test/Makefile, test/runSvcGenerateTests.py, test/runTests.py
This PR is to update minor bugs and minor enhancements. These include:
-Fixing a typo of the default path to secure variables 
-Edited compiler optimization from -Os to -O2 because -Os was causing issues on ppc (opened a gcc bug report [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98692))
-Allow for custom man page destination during install with `make install MANDIR=<path>`
I also created an easy way to generate key reset files with `secvarctl generate reset -n <varName> -k <signerKey> -c <signerCrt>`
This update has been reflected in documentation.
=> New generate reset key subcommand and minor fixes

README.md, backends/edk2-compat/edk2-svc-generate.c, extraMbedtls/generate-pkcs7.c, extraMbedtls/include/generate-pkcs7.h, secvarctl.1, test/runSvcGenerateTests.py
This PR includes the implementation, documentation, and the testing for secvarctl ability to accept externally signed data. Rather than only supporting signatures computed internally. This will let secvarctl produce the presigned digest, allowing the user to use an external signing framework for the actual signature generation. From there, secvarctl can use this raw signed data when generating an auth or PKCS7 file. The process will look like this:
$ secvarctl generate c:x  -n \<varName> -t \<timestamp> -i \<newCrt> -o \<digest.bin>
$<user generates the signature using another tool, resulting in file \<signature.bin>
$secvarctl generate c:a -n \<varName> -t \<timestamp> -i \<newCrt> -o \<update.auth> -s \<signature.bin> -c \<signingCrt.pem>
NOTE: The timestamp and varName must be the …
=> Add functionality for external signatures

CMakeLists.txt, Makefile, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-verify.c, backends/edk2-compat/edk2-svc-write.c
This commit adds CMakeLists.txt. The user will now have the option to build with Cmake or Make. The Cmake build will have the same options as Make. Static, Debug, Coverage, Custom Mbedtls and  non crypto builds can all be generated with STATIC=On , CMAKE_BUILD_TYPE=Debug, CMAKE_BUILD_TYPE=Coverage, CUSTOM_MBEDTLS=<path>, and NO_CRYPTO=On respectively. This commit also removes the -g option from the Makefile's CFLAGS because it had no impact with the following -s and -O2 flags.
=> CMakeLists.txt: Add Cmake build options

CMakeLists.txt, Makefile, README.md, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-verify.c, backends/edk2-compat/edk2-svc-write.c
This PR will allow for secvarctl to be made with CMake and Make. Previously, only Make was supported,  since the secvarctl tool has grown and is now being packaged for distros, it would be more beneficial to use an auto build tool like CMake. This PR will add the CMakeLists.txt file needed for CMake and the documentation in the README.md so users can compare the build process for Make and CMake. There is also a commit to better call strcpy that avoids errors during packaging for RHEL.
=> Add Cmake Build option

CMakeLists.txt, Makefile, backends/edk2-compat/edk2-svc-generate.c, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-validate.c, backends/edk2-compat/edk2-svc-verify.c, backends/edk2-compat/edk2-svc-write.c, backends/edk2-compat/include/edk2-svc.h, external/extraMbedtls/generate-pkcs7.c, external/extraMbedtls/include/generate-pkcs7.h, external/skiboot/edk2-compat-process.c, generic.c, include/secvarctl.h, secvarctl.c
They were being added in the link flags rather than the compile
flags, so they were not having any effect at all.
I've tried to propagate the `unsigned char` idiom from mbedtls outwards, but not into the skiboot parts just yet.
Signed-off-by: Daniel Axtens <dja@axtens.net>
=> Enable -Wall and -Werror

CMakeLists.txt
This commit will change the default build type to debug. Both debug and coverage have been given additional flags: -Wall and -Werror. The reasoning is that most of the time that the project is built from source, it will be to incorporate/test changes or enhancements. This will encourage all warnings to be fixed before commiting a change. If building for general use, then the Release build type can be used (these flags have not been added here for this reason)
=> CMakeLists.txt: change default build type to Debug

README.md, backends/edk2-compat/edk2-svc-generate.c, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-validate.c, backends/edk2-compat/edk2-svc-verify.c, backends/edk2-compat/edk2-svc-write.c, backends/edk2-compat/include/edk2-svc.h, external/extraMbedtls/generate-pkcs7.c, generic.c, include/generic.h, include/secvarctl.h, secvarctl.1, secvarctl.c, test/runSvcGenerateTests.py
This PR is to replace the current argument parsing scheme with one that incorporates argp. Argp is a package from the GNU C standard library, it greatly reduces the need for argument parsing functions and autogenerates help and usage messages. This PR contains commits that add the argp implementation to each of the subcommands {'read', 'write', 'verify', 'validate', 'generate' }. This PR does not alter or remove any of the current command line arguments. However, it does add long flags for almost all of the options (ex: `-v` can also be specified with `--verbose`). It is very likely that another commit may be added in the future to trim some of the added source code. For example, every subcommand individually creates the 'program name' argument by concatenating the first and second …
=> Use argp for argument parsing

backends/edk2-compat/edk2-svc-verify.c, external/extraMbedtls/generate-pkcs7.c, external/extraMbedtls/pkcs7.c, external/skiboot/secvar_util.c
This pull request contains a series of commits that react to warnings left by various static analysis tools. It is branched off of the openssl Pull Request, available [here](https://github.com/open-power/secvarctl/pull/11), and is therefore dependent on that being merged. The tools used were `cppcheck`,  `scan-build` and gcc's `-fanalyzer` . Most of the commits are very small and mainly deal with freeing or closing memory and files if a rare error occurs (like memory allocation failure). That being said, a bug is a bug and worthy of being patched!
=> Respond to Static Analysis Warnings

backends/edk2-compat/edk2-svc-generate.c, backends/edk2-compat/edk2-svc-read.c, backends/edk2-compat/edk2-svc-validate.c, backends/edk2-compat/edk2-svc-verify.c, backends/edk2-compat/edk2-svc-write.c, backends/edk2-compat/include/edk2-svc.h, external/linux/.clang-format, external/skiboot/include/compiler.h, external/skiboot/libstb/secvar/backend/edk2-compat-process.c, external/skiboot/libstb/secvar/backend/edk2-compat-process.h, external/skiboot/libstb/secvar/backend/edk2.h, generic.c, include/prlog.h, secvarctl.c
This series:
- brings in compiler.h, which is pretty handy.
- brings in edk2.h from skiboot, as it will be if my patches to the list are accepted.
- clean up the pragma pack warnings now that edk2.h doesn't use them
- exports some functions in skiboot and makes them accessible to secvarctl. Sadly this part is not bisectable. The skiboot side of this change was also sent to the list.
=> Further syncing with skiboot

external/extraMbedtls/pkcs7.c
Previously, the pkcs7 code was using sizeof(hash) in pkcs7_verify to store the size of the hash. But, since `hash` is a pointer, the incorrect value (8 instead of 32) was being passed. Mbedtls accepts 0 to use the default value for the hash function (ex: SHA256 == 32 bytes), so this commit makes use of that. Thanks to Daniel Axtens for making this observation.
Signed-off-by: Nick Child <nick.child@ibm.com>
=> pkcs7.c: Respond to bug in sizeof( hash)

Makefile
the binary is installed into /usr/bin and the man page into
/usr/local/man. That does not make any sense.
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> Do not install man pages into /usr/local

backends/edk2-compat/edk2-svc-validate.c, test/runTests.py
When validating the timestamp variable (TS), we run through every entry and return and ensure that the values are logical. Having the year set to zero is invalid. But if the entire 16 byte timestamp is zero, then it technically is valid since it means that there is currently no entries for that secvar.
This commit adds a check to allow for empty ts entries when validating the TS variable
Signed-off-by: Nick Child <nick.child@ibm.com>
=> edk2-svc-validate.c: Allow empty timestamp in timestamp validation

external/skiboot/libstb/secvar/backend/edk2-compat.c, test/runTests.py
Previously, we are commmenting out the section of code that enforced secure boot if the the PK is updated. I likely thought it was HW key related so I commented it out. I uncommented so now secure boot will be enforced as soon as a PK is enrolled.
This needs a test case but is a bug so opening the PR now.
=> BUG: edk2-compat.c: Turn on setup mode if PK is updated

backends/edk2-compat/edk2-svc-verify.c, test/runTests.py
Previously, if an empty (size 0) secvar existed in the sysfs, it was added to the current variable bank (see `setupBanks()`). This leads to errors in `validateBanks` because it calls `validateESL` on all entries in the current variable bank. `validateESL` returns an error if there is no data in the esl. This means that if there is no data in the current KEK, the verify function will return early on an error that the contained data in KEK/data is not a valid ESL. This commit, omits empty secvars from the current list of variables since an empty secvar is a common thing in Secure Boot and should not be treated as an error.
Signed-off-by: Nick Child <nick.child@ibm.com>
=> edk2-svc-verify.c: Do not add empty secvars to variable bank

backends/edk2-compat/edk2-svc-validate.c, external/skiboot/libstb/secvar/crypto/crypto-openssl.c
This pull request is to fix a bug identified by @daxtens . Thanks Daniel.
There were two issues in the openssl implementation of `crypto_x509_is_RSA`.
First, the function would return NULL on an error which would be converted to 0 
when typecast to an int. This would slip through the conditionals and return as a success.
Second, we were attempting to read the signature algorithm used to sign the x509, in reality
we wanted to get the type of the public key.
=> crypto: Fix openssl implementation of crypto_x509_is_RSA

CMakeLists.txt, Makefile, README.md, backends/edk2-compat/edk2-svc-validate.c, external/skiboot/libstb/secvar/crypto/crypto-gnutls.c, external/skiboot/libstb/secvar/crypto/crypto.h, test/Makefile, test/runSvcGenerateTests.py
With this pull request, secvarctl can now be built with `make GNUTLS=1` for using GnuTLS as the crypto library. From a user perspective, there are no differences with API. Just like with openssl builds, all crypto calls work except for generating a  PKCS7 with a signature blob instead of a private key. This is simply because the libraries do not have any support for doing this. The gnutls implementation of the crypto abstraction functions are all pretty straight forward. Except for the hashing context and pkcs7 structs, those both got funky for two different reasons:
1. I had to implement a hacky `crypto_md_ctx` since gnutls does not have one publicly available. You can only give a tbh buffer and get the output. So, I just had `crypto_md_ctx` be a structure where the user could …
=> Add support for compiling with GnuTLS as crypto library

backends/edk2-compat/edk2-svc-generate.c, backends/edk2-compat/edk2-svc-validate.c, external/skiboot/libstb/secvar/backend/edk2-compat-process.c, external/skiboot/libstb/secvar/crypto/crypto-gnutls.c, external/skiboot/libstb/secvar/crypto/crypto-mbedtls.c, external/skiboot/libstb/secvar/crypto/crypto-openssl.c, external/skiboot/libstb/secvar/crypto/crypto.h
This pull request is dependent on #33 
This pull request is a result of conversation from #30 .
Previously, both secvarctl and openssl/mbedtls/gnutls error codes were being returned from the crypto abstraction functions.
This PR will only return openssl/mbedtls/gnutls error codes.
Additionally, the calling functions were changed to expect `CRYPTO_SUCCESS` if the crypto abstraction function executed without errors. This allows us to set `CRYPTO_SUCCESS` to something specific to the imported library (it just so happens to be zero for mbedtls, gnutls and openssl) rather than always returning a secvarctl defined success value.
=> Unify crypto return values

.github/workflows/CI_formatting.yml, .github/workflows/build_rpm.yml, .github/workflows/x86_CI.yml
Hello,
This pull request adds two new workflows to secvarctl:
1. run CI tests on every push and pull request
2. build x86 rpm and source rpm on every release
Some notes on these:
- CI tests run  on an Ubuntu x86 github runner, it does not seem that github supports actions on other architectures
- I initially thought I could cross compile a ppc64le rpm, it builds but when I try to install on a ppc64le machine I fail to install
- Since ppc64le rpm is failing, for now I commented that part of the workflow out and figured the source rpm would be sufficient
=> Add github actions for CI testing and building rpm's

Makefile, backends/guest/common/generate.c, backends/guest/common/read.c, backends/guest/common/util.c, backends/guest/common/validate.c, backends/guest/common/verify.c, backends/guest/guest_svc_generate.c, backends/guest/guest_svc_read.c, backends/guest/guest_svc_verify.c, backends/host/host_svc_generate.c, backends/host/host_svc_read.c, backends/host/host_svc_validate.c, backends/host/host_svc_verify.c, generic.c, include/generic.h
This PR adds a new `make cppcheck` build target to run the `cppcheck` static analysis tool on the source files. The rest of this PR is a fix for every single complaint it had, including a few found from `scan-build`.
---
Some highlights:
- a LOT of incorrect format strings, mostly using `%d` with unsigned integers (`%u`). Commit messages started getting lazier with these.
- a worrying amount of `unsigned < 0` comparisons. May warrant a larger audit of all size checks and size arithmetic, I fear there may be possible cases of unsigned wrapping.
- a few function overhauls, as the errors that were reported were too messy to fix in a simple manner. These should have more detailed commit messages
---
NOTE: A subsequent PR will re-enable Actions, and will run both of these tools.
=> Static Analysis Fixes

.gitignore, Makefile, test/Makefile, test/guest/guest_generate_testdata.py, test/guest/guest_tests.py, test/host/runSvcGenerateTests.py, test/host/runTests.py
Depends on #44 
Valgrind is a great tool, but has a lot of runtime overhead -- especially at startup. We make probably hundreds of calls to `secvarctl`, and therefore invoke valgrind hundreds of times, causing a large amount of time waiting for valgrind to initialize.
This PR adds new support to the `Makefile` for building with address and undefined behavior sanitizers, which introduce a negligible amount of overhead to running the binary, with the benefit of catching even more problems than valgrind.
This comes with a free rework to how testing/debuild builds are handled:
- `secvarctl-cov` has been renamed to `secvarctl-dbg` (and corresponding build targets)
- `make debug` is aliased to building the debug binary
- all `.cov.o` objects are now `.dbg.o`
- debug build now enables coverage, …
=> Replace valgrind with ASAN/UBSAN, overhaul debug build

backends/guest/common/generate.c, backends/guest/common/read.c, backends/guest/common/util.c, backends/guest/common/validate.c, backends/guest/common/verify.c, backends/guest/guest_svc_generate.c, backends/guest/guest_svc_read.c, backends/guest/include/common/read.h, backends/guest/include/common/util.h, backends/host/host_svc_generate.c
Depends on #45 , #44 . I goofed on opening the PRs in the right order, merge this before #46 
Apply fixes reported by ASAN/UBSAN.
There are two major reworks included in this, a few smaller ones:
- replace use of signature type strings with an enum to remove a ton of unnecessary `memcmp`/`strcmp`
- change use of `uint8_t*` as a string type to `char*`
- fixed a few memory leaks
- fixed `memcpy` from `NULL` UB
=> ASAN Fixes

.github/workflows/x86_CI.yml, .gitignore, CMakeLists.txt, Makefile, backends/guest/CMakeLists.txt, backends/host/CMakeLists.txt
The original CMake build implementation allowed for easier packaging, so for the same reason, re-implement the CMake build now that some of the architectural problems with guest/host code has been sorted out.
The goals for this implementation are as follows:
- provide an alternative for simple builds to the Makefile
- easier integration into packaging systems (e.g. rpmbuild)
This is *NOT* intended to be feature-parity with the Makefile, as (at the moment), running tests and other pseudo-targets are much easier done with simple make rules.
Marking as a draft for now, since I'm assuming there's features missing still. Please take a look and see if there are any critical missing features.
At the moment, the following features are not implemented, and may not be for the scope of this PR:
- …
=> Reimplement CMake-based build system

CMakeLists.txt, Makefile, backends/guest/CMakeLists.txt, backends/guest/Makefile.inc, backends/host/CMakeLists.txt, backends/host/Makefile.inc
This PR is not based on #49 , and may have minor conflicts. Since this one is much smaller, consider reviewing and merging this one first.
This PR reworks the build system to support selecting which backend to use, and which crypto library to link against.
Major changes:
- split backend-specific dependencies into their respective makefile/cmake include files
- remove unneeded files for a build, such as the extra mbedtls pkcs7
- start the process of splitting the crypto implementations, though that will really depend on the forthcoming crypto library rework
- (Makefile): replace the `OPENSSL=1`, `MBEDTLS=0`, etc options with a single `CRYPTO=openssl` variable
---
Now that single backends have been implemented, and crypto library selection "in place": this is a good opportunity to really …
=> More build tweaks, single backend edition

secvarctl.spec
Here's a spec file that successfully builds and packages secvarctl.  I've tested it on RHEL 8.7 and it should work on RHEL 9 and Fedora.
=> Add secvarctl.spec in order to build RPMs

.github/workflows/CI_formatting.yml, .github/workflows/x86_CI.yml, backends/guest/include/guest_svc_backend.h, backends/host/host_svc_backend.h, include/secvarctl.h, secvarctl.c, test/common.py, test/guest_tests.py, test/host_generate_tests.py, test/host_tests.py
Opening this PR so I don't forget/lose the branch, but it's lower priority.
---
This PR changes three major components:
- rewrite secvarctl backend selection logic, to make it easier to manage disabling certain backends
- have tests skip if the target backend is not supported
- use a matrix strategy to additionally test single-backend builds
---
There is one major side effect to the `secvarctl.c` rewrite: the `-m` flag is now mandatory when running on a non-secure boot enabled POWER system (i.e. x86). This is largely because the tool should not make assumptions on what backend to use, nor should it "default" to one, which may lead to unexpected behavior.
Currently, the mode flag is still required for a single-backend build. Personally, I'm of the opinion that it should be required even in …
=> Improve single-backend builds, allow for testing single-backends, update CI

backends/guest/guest_svc_read.c, test/guest_tests.py
Fixes #62.
Paths supplied to read are expected to contain a trailing slash, which is a regression from previous versions. Change get_variable_path to automatically insert a trailing slash if needed.
Note: this function is a candidate for factoring out into common code, I suspect this behavior might be present in other bits of backend code.
=> guest/read: allow paths with or without a trailing slash

backends/guest/guest_svc_generate.c, guest-usage.md
Fixes #65.
Currently, the -a --append option accepts a string to be parsed into an integer, either 0 or 1. This integer is then used to set a boolean append flag.
Avoid parsing strings at all by having the boolean append flag be set to 1 if -a/--append exists, otherwise default to 0.
NOTE: This does introduce a change in the command line API.
---
This one is a slightly more invasive change, but I think the removal of needless string parsing is better for overall safety. Please let me know if you disagree with this approach.
=> guest/generate: change --append option to be a boolean based on presence

backends/guest/common/generate.c, backends/guest/common/read.c, backends/guest/common/util.c, backends/guest/common/validate.c, backends/guest/include/common/generate.h, backends/guest/include/common/util.h, test/guest_tests.py
In essence, generating an ESL with hash contents was totally broken but returned success.
=> Nick misc bugs

backends/guest/guest_svc_generate.c
Addresses #65 
There can only be one PK, therefore the PK cannot be appended to. However, the current error message is not clear, and references the older method of setting the flag. Furthermore, this error is handled in the same way as an invalid argument parse which leads to the whole usage information being printed, which makes finding the error message difficult.
This commit rewords the error message to be a little more clear, and moves the special case check for PK appends outside of the rest of the argument validation logic, thus avoiding the extra usage output.
=> guest/generate: reword error message for disallowing PK appends

Makefile, backends/guest/common/generate.c, backends/guest/common/read.c, backends/guest/common/util.c, backends/guest/common/validate.c, backends/guest/common/verify.c, backends/guest/common/write.c, backends/guest/guest_svc_generate.c, backends/guest/guest_svc_read.c, backends/guest/guest_svc_validate.c, backends/guest/guest_svc_write.c, backends/guest/include/common/util.h, backends/guest/include/common/verify.h, backends/guest/include/common/write.h, backends/host/host_svc_generate.c, backends/host/host_svc_read.c, backends/host/host_svc_validate.c, backends/host/host_svc_verify.c, backends/host/host_svc_write.c, external/skiboot/libstb/secvar/backend/edk2-compat-process.c, external/skiboot/libstb/secvar/backend/edk2-compat-process.h, external/skiboot/libstb/secvar/backend/edk2-compat.c, external/skiboot/libstb/secvar/secvar.h, external/skiboot/libstb/secvar/secvar_util.c, generic.c, include/generic.h, secvarctl.c
Buffer types are inconsistent across the project -- some bits use `char *`, `unsigned char *`, `uint8_t *`, etc. This PR attempts to unify all buffer types to use the same type to avoid needless casting.
The following has been done:
- use `uint8_t *` for raw pointers to data (buffers)
- use `char *` for strings and (hopefully) *only* strings
- comment the few cases where a cast is necessary
- this is primarily when loading data from a file that IS a string, or similar cases
---
Due to laziness on my part, I'm also piggybacking some static analysis fixes into this PR. These checks are not reported by the version of cppcheck that actions uses (2.7), but are included in the newer 2.12 version.
The changes are mostly minor:
- ignore checking ccan headers, as we will not be amending those
- …
=> Type Usage Overhaul + Assorted Static Analysis Fixes

backends/guest/common/generate.c, backends/guest/common/read.c, backends/guest/common/util.c, backends/guest/common/validate.c, backends/guest/common/verify.c, backends/guest/guest_svc_generate.c, backends/guest/guest_svc_read.c, backends/guest/guest_svc_validate.c, backends/guest/guest_svc_verify.c, backends/guest/include/common/generate.h, backends/guest/include/common/util.h, backends/guest/include/common/validate.h
Supercedes #75, can be closed when this is merged. This PR contains a set of amended commits, largely squashed down intermediate commits, and applied the fixes as suggested in the previous PR.
---
Notable changes from #75:
- squashed unnecessary intermediate commits
- added a comment about the version byte to `read_timestamp()`, further information and work can be tracked in #76 
- restored `else` error cases that were removed for some reason
- rebased onto `guest-devel`
- restored returning `INVALID_FILE` from `guest_current_esl_data` in `common/verify.c`
=> Add missing patches from internal version, redux

backends/guest/guest_svc_read.c, test/guest_tests.py
Addresses #78 
`is_trustedcadb_variable()` expects a non-NULL string as an argument, however `read -c <file>` does not set a variable name, as it is just a file with no context. This bug was introduced by my amendments to the initial version of the missing features PR #77 , where I simplified the `is_trustedcadb_variable()` to be a single call to `strcmp()`.
Fix the regression, by adding a NULL check before calling `is_trustedcadb_variable()`.
---
This also led me to discover another fun point: the test cases did not correctly pick up and test `.crt` files as it should have, and instead was looking for `.cert` files. This has also been addressed, which should have caught this regression before it landed in `-rc3`.
=> Fix regression cert file read regression in rc3

backends/guest/guest_svc_generate.c, test/Makefile, test/common.py, test/guest_tests.py
Fixes #80 
Argp calls the `parse_options()` function for each argument, therefore the logic to reject the append flag on a PK was evaluated for other arguments. Move the append flag reject logic outside of the argument parser, since it only needs to be evaluated once anyway, after all arguments have been read.
---
While solving the above, I noticed that the positional format specifier argument parsing logic was fairly... lacking. It led to some confusing error messages, as the original test case was using the old `-a 0` syntax for specifying the append header. The `0` was treated as a positional argument, and therefore was expected to be in the `c:a` format. Since it was _not_, it overwrote the previously valid `c:a` format specifier with `NULL`s, leading to an error in the format …
=> Fix generate argument parsing

backends/guest/common/read.c
Minor fix. In guest mode, when printing a variable that has been cleared, a scary error message is printed claiming there is no remaining space to unpack an ESL.
```
$ ./bin/secvarctl -m guest read -n dbx -p tmp
READING dbx :
Timestamp: 2023-04-07 09:18:56 UTC
Not enough space left for an ESL when unpacking buffer: 0 bytes remain
Error reading from esl buffer: 1
RESULT: FAILURE
```
Since the variable has been cleared, there obviously is no data, therefore the buffer is empty, however there is still the timestamp that should be printed. Therefore, handle cases when printing an empty buffer to indicate that there is no data to print:
```
$ ./bin/secvarctl -m guest read -n dbx -p tmp
make: Nothing to be done for 'all'.
READING dbx :
Timestamp: 2023-04-07 09:18:56 UTC
(empty)
RESULT: SUCCESS …
```
=> Don't attempt to print an ESL from a zero-sized buffer

test/guest_generate_testdata.py
Added directory fix for the given error- No such file or directory: '../../bin/secvarctl-dbg'.
****
Error Log:- 
[root@ test]# python3 guest_generate_testdata.py
Traceback (most recent call last):
File "/home/secvarctl/test/guest_generate_testdata.py", line 244, in <module>
create_goldenkey_files ()
File "/home/secvarctl/test/guest_generate_testdata.py", line 135, in create_goldenkey_files
generate_esl (var_name, format_type, cert_file, esl_file)
File "/home/secvarctl/test/guest_generate_testdata.py", line 80, in generate_esl
command (secvarctl + [format_type, "-i", cert_file, "-o", esl_file, "-n", variable_name])
File "/home/secvarctl/test/guest_generate_testdata.py", line 61, in command
return subprocess.call (args, stderr=err, stdout=out)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
=> Added fix for secvarctl-dbg directory in guest_generate_testdata.py

test/guest_generate_testdata.py
As reported in #89 test data generated by `guest_generate_testdata.py` do not pass the guest test cases. The culprit was a simple directory name typo: `goldenkeys` vs `goldenKeys`. However, as this file was in serious need of clean up, took the time to fix it up as well -- mostly fixing style issues, indentation problems (which I'm rather confused on how this ran in the first place, knowing how picky python is), and other bits of redundant code.
There's still a few more things that can probably be cleaned up in this file, I may add a few more commits to this PR before merging.
=> Clean up and fix `guest_generate_testdata.py`

CMakeLists.txt, Makefile, README.md, backends/guest/Makefile, backends/guest/common/validate.c, backends/guest/guest_svc_generate.c, backends/guest/guest_svc_read.c, backends/host/host_svc_generate.c, backends/host/host_svc_read.c, backends/host/host_svc_validate.c, external/skiboot/libstb/secvar/crypto/crypto-gnutls.c, external/skiboot/libstb/secvar/crypto/crypto-mbedtls.c, secvarctl.c
Originally, SECVAR_CRYPTO_WRITE_FUNC was intended to be a compile-time flag to remove any generation code, to reduce the resulting binary file size to be as small as possible for management-only uses (such as in embedded firmware environment, like Petitboot).
Builds like these never came about, and this option only made builds more complex and error prone, so remove it.
Also fix a few cppcheck errors that popped up, since apparently not all branches were being checked.
Closes #83
=> treewide: remove SECVAR_CRYPRO_WRITE_FUNC
